"""empty message

Revision ID: 06a215872d69
Revises: 9402a5a7a635
Create Date: 2020-06-30 00:32:45.075439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06a215872d69'
down_revision = '9402a5a7a635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circletask_blocks', sa.Column('rating', sa.Integer(), nullable=True, comment="The user's perceived difficulty of the block on a Likert Scale. Very easy - 0,  Easy - 1,  Neutral - 2, Difficult - 3, Very difficult - 4"))
    op.add_column('users', sa.Column('gaming_exp', sa.Integer(), nullable=True, comment='How much experience with two-handed mobile games does the user have? daily, several times a week, several times a month, several times a year, never'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gaming_exp')
    op.drop_column('circletask_blocks', 'rating')
    # ### end Alembic commands ###
