"""'init'

Revision ID: 36dd0a57afb9
Revises: 
Create Date: 2019-07-12 20:51:42.467462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dd0a57afb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('screen_x', sa.Integer(), nullable=True),
    sa.Column('screen_y', sa.Integer(), nullable=True),
    sa.Column('dpi', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('size_x', sa.Float(), nullable=True),
    sa.Column('size_y', sa.Float(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ct_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('treatment', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('time_iso', sa.DateTime(), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('circle_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('trial', sa.Integer(), nullable=False),
    sa.Column('df1', sa.Float(), nullable=True),
    sa.Column('df2', sa.Float(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['ct_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circle_tasks')
    op.drop_table('ct_sessions')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
