"""empty message

Revision ID: 4fb7eb60d4ed
Revises: 6766d4c4d0ed
Create Date: 2020-06-06 22:44:09.263410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb7eb60d4ed'
down_revision = '6766d4c4d0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ct_sessions', sa.Column('nth_session', sa.Integer(), nullable=False))
    op.add_column('ct_sessions', sa.Column('session_uid', sa.String(length=32), nullable=False))
    op.drop_column('ct_sessions', 'session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ct_sessions', sa.Column('session', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ct_sessions', 'session_uid')
    op.drop_column('ct_sessions', 'nth_session')
    # ### end Alembic commands ###
