"""empty message

Revision ID: 6766d4c4d0ed
Revises: f5fe574b2b8b
Create Date: 2020-06-05 01:03:39.413353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6766d4c4d0ed'
down_revision = 'f5fe574b2b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle_tasks', sa.Column('df1_duration', sa.Float(), nullable=True))
    op.add_column('circle_tasks', sa.Column('df1_grab', sa.Float(), nullable=True))
    op.add_column('circle_tasks', sa.Column('df1_release', sa.Float(), nullable=True))
    op.add_column('circle_tasks', sa.Column('df2_duration', sa.Float(), nullable=True))
    op.add_column('circle_tasks', sa.Column('df2_grab', sa.Float(), nullable=True))
    op.add_column('circle_tasks', sa.Column('df2_release', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circle_tasks', 'df2_release')
    op.drop_column('circle_tasks', 'df2_grab')
    op.drop_column('circle_tasks', 'df2_duration')
    op.drop_column('circle_tasks', 'df1_release')
    op.drop_column('circle_tasks', 'df1_grab')
    op.drop_column('circle_tasks', 'df1_duration')
    # ### end Alembic commands ###
