"""empty message

Revision ID: 9402a5a7a635
Revises: b8288d7a7d3e
Create Date: 2020-06-19 04:37:04.265886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9402a5a7a635'
down_revision = 'b8288d7a7d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age_group', sa.String(length=5), nullable=True, comment='Approximate age of user.'))
    op.add_column('users', sa.Column('gender', sa.String(length=1), nullable=True, comment="Gender identification of user."))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age_group')
    # ### end Alembic commands ###
