"""'ctsession_props'

Revision ID: f5fe574b2b8b
Revises: 26593a115a73
Create Date: 2019-07-25 02:13:46.154134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fe574b2b8b'
down_revision = '26593a115a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ct_sessions', sa.Column('cool_down', sa.Float(), nullable=False))
    op.add_column('ct_sessions', sa.Column('trial_duration', sa.Float(), nullable=False))
    op.add_column('ct_sessions', sa.Column('warm_up', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ct_sessions', 'warm_up')
    op.drop_column('ct_sessions', 'trial_duration')
    op.drop_column('ct_sessions', 'cool_down')
    # ### end Alembic commands ###
